$schema: /home/omer/devel/taskrunner/schemas/taskrunner_v0.11.json
tasks:
  test:
    short_desc: Run test
    commands:
      - tests/runtests {{cliArgs}}
    cwd: '{{taskRoot}}'
  build:
    short_desc: Build package
    commands:
      - rm -rf dist
      - python3 -m build
    cwd: '{{taskRoot}}'
  upload-testpypi:
    short_desc: Build package to testpypi
    commands:
      - python3 -m twine upload --repository testpypi dist/*
    cwd: '{{taskRoot}}'
  upload-pypi:
    short_desc: Build package to pypi
    commands:
      - python3 -m twine upload dist/*
    cwd: '{{taskRoot}}'
  test_pkg_base:
    short_desc: Basic package test
    commands:
      - '{{taskRoot}}/tests/run_pkg_tests'
    abstract: true
  test_pkg_testpypi:
    short_desc: Basic package test from testpypi
    base: test_pkg_base
    env:
      TEST_PYPI: "1"
  test_pkg_pypi:
    short_desc: Basic package test from pypi
    base: test_pkg_base
    env:
      TEST_PYPI: "0"
default_task: test
default_container_tool: /usr/bin/podman
use_default_include: false
