#!/bin/bash

# Stupid Apple
if [[ ${OSTYPE} == 'darwin'* ]]; then
	READLINK="greadlink"
else
	READLINK="readlink"
fi

SCRIPT_FILE="$(${READLINK} -f ${BASH_SOURCE[0]})"
SCRIPT_DIR="$(dirname $SCRIPT_FILE)"

python3 ${SCRIPT_DIR}/tr_test.py "$@"
