_MAJOR_VER = 0
_MINOR_VER = 8
_FIX_VER = 0
_BUILD_VER = 0
TR_BASE_VERSION = f'{_MAJOR_VER}.{_MINOR_VER}.{_FIX_VER}'
TR_FULL_VERSION = f'{_MAJOR_VER}.{_MINOR_VER}.{_FIX_VER}-{_BUILD_VER}'
__VERSION__ = TR_FULL_VERSION
