name: test-with-packages
on: workflow_dispatch
defaults:
  run:
    shell: bash
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytaskrunner
          podman pull docker.io/rockylinux/rockylinux:8.5
          podman pull docker.io/library/ubuntu:20.04
      - name: Run test
        run: |
          rm task task.py # Just for kicks, so it wouldn't run it by mistake
          tests/tr_test --pkg --no-colors
  darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          brew install coreutils
          python -m pip install --upgrade pip
          pip install pytaskrunner
      - name: Run test
        run: |
          rm task task.py
          tests/tr_test --pkg --no-colors --no-containers
